### ISSUE TITLE
Example on tinymce configuration

### ISSUE THREAD

**Issue by SantoshSrinivas79** [isotoma/wagtailtinymce#11]
Could you please provide an example to [customize tinymce](https://github.com/isotoma/wagtailtinymce#tinymce-configuration)?

Sorry .. new to this stuff

**Comment by SantoshSrinivas79** [comment]
@nfletton @riceyrice .. could you pls advise on this?
I basically want to display the "code" button in the editor for all editors across the site.
What would be the best way to do this?

**Comment by dprothero** [comment]
@SantoshSrinivas79 I know you opened this a while ago, but here's how I added the "code" button:

``` python
class TwilioTinyMCERichTextArea(TinyMCERichTextArea):
    def __init__(self, attrs=None, **kwargs):
        super(TwilioTinyMCERichTextArea, self).__init__(attrs, **kwargs)
        buttons = self.kwargs['buttons']
        buttons[0].append(['code'])
```

And then in my config:

``` python
WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'default': {
        'WIDGET': 'core.widgets.TwilioTinyMCERichTextArea'
    },
}
```

You can see the default options that this plugin configures here:
https://github.com/isotoma/wagtailtinymce/blob/master/wagtailtinymce/rich_text.py#L41-L62

**Comment by SantoshSrinivas79** [comment]
@dprothero Thank you!
