### ISSUE TITLE
Use Wagtail's new configurable RTE hooks

### ISSUE THREAD

**Issue by tomdyson** [isotoma/wagtailtinymce#2]
Hi Isotoma! 

Configurable rich text editors (https://github.com/torchbox/wagtail/pull/2416) is landing in Wagtail 1.5, which is currently available in release candidate. We hope this will make `wagtailtinymce` possible, without your https://github.com/torchbox/wagtail/pull/1521 refactor. It'd be great to announce TinyMCE support, via your module, at the same time as the 1.5 release at the start of next week - is that feasible?

Thanks

Tom

**Comment by tomdyson** [comment]
P.S. you can test the 1.5 RC with `pip install wagtail==1.5rc1`

**Comment by riceyrice** [comment]
Challenge accepted. We are taking a look at this now.

**Comment by riceyrice** [comment]
Do you still expect to add an `OPTIONS` key for each editor in settings? e.g. passed as an `options` argument to the widget constructor if present in the setting?

**Comment by riceyrice** [comment]
It is done!

**Comment by riceyrice** [comment]
It is done! Thanks to @mitchellrj and @waldo90 for their assistance in turning this round.

**Comment by SantoshSrinivas79** [comment]
@riceyrice @tomdyson I need to add a "code" option in the buttons of the editor. I am using `wagtailmce` by default ..

``` py
WAGTAILADMIN_RICH_TEXT_EDITORS = {
    'default': {
        'WIDGET': 'wagtailtinymce.rich_text.TinyMCERichTextArea'
    },
}
```

Is there a easy way to do this?
